# Generated by Django 5.2.17 on 2026-08-19 09:16

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField(validators=[django.core.validators.MaxValueValidator(444), django.core.validators.MinValueValidator(2)])),
                ('etage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('nb_places', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('hours', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('date', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.carrel')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.creneau')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'carrel', 'creneau')},
            },
        ),
    ]
