# Generated by Django 5.2.17 on 2026-08-19 11:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_alter_reservation_etudiant_delete_etudiant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrel',
            new_name='Carel',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='carrel',
            new_name='carel',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('etudiant', 'carel', 'creneau')},
        ),
    ]
